### ISSUE TITLE
我不想考了

### ISSUE THREAD

**Issue by aesophor** [a4865g/GPE-Fucker#3]
T_T 救我

**Comment by a4865g** [comment]
This is your problem. >_o

**Comment by aesophor** [comment]
![Screen Shot 2021-10-13 at 4 41 02 PM](https://user-images.githubusercontent.com/32998585/137098509-3f68fc3f-3502-4c63-b05c-82c157dc656f.png)

**Comment by aesophor** [comment]
真爽 ez game

**Comment by a4865g** [comment]
![image](https://user-images.githubusercontent.com/43570004/138043627-d3630320-eba9-45da-b996-0d95b7ee6f2c.png)
